import express from "express";
import {
  addGroupMember,
  addMemberToGroupByLink,
  addRecipeToGroup,
  createGroup,
  deleteGroup,
  editGroupDetails,
  getGroupRecipeById,
  getGroupRecipesPreview,
  getInviteLink,
  getUserGroups,
  removeGroupMember,
  removeRecipeFromGroup,
  updateAdminStatus,
  updateImageOfGroup,
} from "../controllers/groupController";
import {
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkIsUserGroupMemberMiddleware,
  checkIsGroupMemberAndOwnerRecipeMiddleware,
  checkIsGroupMemberAndOwnerOrAdminMiddleware,
  checkUserIsAdminOfGroupMiddleware,
  checkIsRecipeAndUserGroupMemberMiddleware,
  checkIsMemberGroupMemberMiddleware,
} from "../middleware/authMiddleware";
import { searchLimiter } from "../middleware/rateLimiterMiddleware";
import { sanitizeRequestMiddleware } from "../middleware/sanitazeHtmlMiddleware";
import {
  validateGroupBody,
  validateIdParams,
} from "../middleware/validateMiddleware";
import { singleImageUpload } from "../middleware/uploadMiddleware";

const router = express.Router();

router.get(
  "/",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  searchLimiter,
  getUserGroups
);
router.get(
  "/:groupId",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkIsUserGroupMemberMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateIdParams,
  getGroupRecipesPreview
);
router.post(
  "/",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateGroupBody,
  createGroup
);
router.put(
  "/:groupId",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkUserIsAdminOfGroupMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateIdParams,
  validateGroupBody,
  editGroupDetails
);
router.delete(
  "/:groupId",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkUserIsAdminOfGroupMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateIdParams,
  deleteGroup
);
router.put(
  "/:groupId/recipe/:recipeId/add",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkIsGroupMemberAndOwnerRecipeMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateIdParams,
  addRecipeToGroup
);
router.put(
  "/:groupId/recipe/:recipeId/remove",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkIsGroupMemberAndOwnerOrAdminMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateIdParams,
  removeRecipeFromGroup
);
router.put(
  "/image/:groupId",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkUserIsAdminOfGroupMiddleware,
  searchLimiter,
  singleImageUpload,
  sanitizeRequestMiddleware,
  validateIdParams,
  updateImageOfGroup
);
router.post(
  "/:groupId/link",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkUserIsAdminOfGroupMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateIdParams,
  getInviteLink
);
router.post(
  "/join",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  addMemberToGroupByLink
);
router.put(
  "/:groupId/user/:userId/add",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkUserIsAdminOfGroupMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateIdParams,
  addGroupMember
);

router.put(
  "/:groupId/user/:userId/remove",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkIsGroupMemberAndOwnerOrAdminMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateIdParams,
  removeGroupMember
);
router.get(
  ":groupId/recipe/:recipeId",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkIsRecipeAndUserGroupMemberMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateIdParams,
  getGroupRecipeById
);
router.put(
  "a/:groupId/member/:memberId/",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkUserIsAdminOfGroupMiddleware,
  checkIsMemberGroupMemberMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateIdParams,
  updateAdminStatus
);

export default router;
