import express from "express";
import {
  createRecipe,
  deleteRecipe,
  editRecipe,
  editRecipeImage,
  getPreviewRecipes,
  getRecipeById,
  getRecipesName,
  getRecipesPreviewByCategory,
  getSomeRecipesById,
  removeLikeFromRecipe,
  toggleRecipePrivacy,
  upsertLikeToRecipe,
} from "../controllers/recipesController";
import {
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkRecipeOwnerShipMiddleware,
} from "../middleware/authMiddleware";
import { searchLimiter } from "../middleware/rateLimiterMiddleware";
import { sanitizeRequestMiddleware } from "../middleware/sanitazeHtmlMiddleware";
import { singleImageUpload } from "../middleware/uploadMiddleware";
import {
  validateIdParams,
  validateLikeBody,
  validateRecipe,
  validateRecipeIdsBody,
  validateSearchQuery,
} from "../middleware/validateMiddleware";
import { upsertLikeToRecipeService } from "../services/recipeService";

const router = express.Router();

router.get(
  "/my/search",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateSearchQuery,
  getRecipesName(true)
);
router.get(
  "/search",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateSearchQuery,
  getRecipesName(false)
);
router.get(
  "/recipe/:recipeId",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  sanitizeRequestMiddleware,
  searchLimiter,
  validateIdParams,
  getRecipeById
);
router.post(
  "/recipes",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateRecipeIdsBody,
  getSomeRecipesById
);
router.get(
  "/me/preview",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateSearchQuery,
  getPreviewRecipes(true)
);
router.get(
  "/preview",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateSearchQuery,
  getPreviewRecipes(false)
);
router.post(
  "/",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  searchLimiter,
  singleImageUpload,
  sanitizeRequestMiddleware,
  validateRecipe,
  createRecipe
);
router.put(
  "/:recipeId",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkRecipeOwnerShipMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  sanitizeRequestMiddleware,
  validateIdParams,
  validateRecipe,
  editRecipe
);
router.delete(
  "/:recipeId",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkRecipeOwnerShipMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateIdParams,
  deleteRecipe
);
router.put(
  "/image/:recipeId",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkRecipeOwnerShipMiddleware,
  searchLimiter,
  singleImageUpload,
  sanitizeRequestMiddleware,
  validateIdParams,
  editRecipeImage
);
router.get(
  "/category/:categoryId",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateIdParams,
  validateSearchQuery,
  getRecipesPreviewByCategory
);
router.put(
  "/t/:recipeId",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  checkRecipeOwnerShipMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateIdParams,
  toggleRecipePrivacy
);
router.post(
  "/like/:recipeId",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateIdParams,
  validateLikeBody,
  upsertLikeToRecipe
);
router.delete(
  "/unlike/:recipeId",
  authenticateTokenMiddleware,
  authorizeUserAndExistMiddleware,
  searchLimiter,
  sanitizeRequestMiddleware,
  validateIdParams,
  removeLikeFromRecipe
);

export default router;
